import React, { createContext, useContext, useState, useEffect, useCallback, ReactNode } from "react";

export type Language = "vi" | "en" | "zh" | "ja" | "ko" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LANGUAGE_KEY = "angel-language";

const SUPPORTED_LANGUAGES: Language[] = ["vi", "en", "zh", "ja", "ko", "fr"];

// Translation dictionaries organized by module
const translations: Record<Language, Record<string, string>> = {
  vi: {
    // Navigation
    "nav.home": "Trang chủ",
    "nav.settings": "Cài đặt",
    "nav.profile": "Hồ sơ",
    "nav.help": "Trợ giúp",
    "nav.community": "Cộng đồng",
    "nav.testimonials": "Lời chứng",
    "nav.studio": "Studio",
    "nav.friends": "Bạn bè",
    "nav.credits": "Tín dụng",
    
    // Common buttons
    "common.save": "Lưu",
    "common.cancel": "Hủy",
    "common.continue": "Tiếp tục",
    "common.back": "Quay lại",
    "common.done": "Xong",
    "common.close": "Đóng",
    "common.confirm": "Xác nhận",
    "common.delete": "Xóa",
    "common.edit": "Sửa",
    "common.send": "Gửi",
    "common.submit": "Gửi",
    "common.search": "Tìm kiếm",
    "common.next": "Tiếp",
    "common.previous": "Trước",
    "common.yes": "Có",
    "common.no": "Không",
    "common.ok": "OK",
    "common.note": "Ghi chú:",
    
    // Common messages
    "common.loading": "Đang tải...",
    "common.error": "Đã xảy ra lỗi",
    "common.errorTryAgain": "Đã xảy ra lỗi. Vui lòng thử lại.",
    "common.success": "Thành công",
    "common.noData": "Không có dữ liệu",
    "common.empty": "Trống",
    "common.emptyList": "Danh sách trống",
    "common.noResults": "Không có kết quả",
    "common.confirmDelete": "Bạn có chắc chắn muốn xóa?",
    "common.unsavedChanges": "Bạn có thay đổi chưa lưu",
    "common.saving": "Đang lưu...",
    "common.saved": "Đã lưu",
    "common.signIn": "Đăng nhập",
    "common.signOut": "Đăng xuất",
    "common.signUp": "Đăng ký",
    
    // Angel presence
    "angel.presence": "Thiên thần đồng hành",
    "angel.greeting": "Xin chào, tôi là Thiên thần của bạn",
    "angel.thinking": "Đang suy nghĩ...",
    "angel.typing": "Đang nhập...",
    "angel.style.classic": "Cổ điển",
    "angel.style.modern": "Hiện đại",
    "angel.style.minimal": "Tối giản",
    "angel.sparkles": "Hiệu ứng lấp lánh",
    "angel.trail": "Vệt sáng",
    
    // Sound settings
    "sound.rain": "Mưa nhẹ",
    "sound.ocean": "Sóng biển",
    "sound.forest": "Rừng",
    "sound.wind": "Gió nhẹ",
    "sound.stream": "Suối",
    "sound.night": "Đêm tĩnh",
    "sound.piano": "Piano nhẹ",
    "sound.healing": "Âm chữa lành",
    "sound.singingBowl": "Chuông bát",
    "sound.templeBells": "Chuông chùa",
    "sound.crystalBowls": "Bát pha lê",
    "sound.silence": "Tĩnh lặng",
    "sound.selectAmbient": "Chọn âm thanh môi trường",
    "sound.volume": "Âm lượng",
    "sound.playing": "Đang phát",
    "sound.stopped": "Đã dừng",
    "sound.category.nature": "Thiên nhiên",
    "sound.category.music": "Âm nhạc",
    "sound.category.sacred": "Linh thiêng",
    
    // Settings page
    "settings.title": "Cài đặt",
    "settings.subtitle": "Cá nhân hóa trải nghiệm linh thiêng của bạn",
    "settings.angel.title": "Thiên thần đồng hành",
    "settings.angel.description": "Tùy chỉnh thiên thần hiền dịu đồng hành cùng bạn",
    "settings.angel.enable": "Bật Thiên thần đồng hành",
    "settings.angel.enableDesc": "Hiển thị thiên thần trên thiết bị máy tính",
    "settings.appearance.title": "Giao diện",
    "settings.appearance.description": "Tùy chỉnh trải nghiệm hình ảnh của Angel AI",
    "settings.appearance.theme": "Chủ đề",
    "settings.appearance.light": "Sáng",
    "settings.appearance.lightDesc": "Giao diện sáng và rõ ràng",
    "settings.appearance.dark": "Tối",
    "settings.appearance.darkDesc": "Dễ nhìn trong ánh sáng yếu",
    "settings.appearance.system": "Hệ thống",
    "settings.appearance.systemDesc": "Theo cài đặt thiết bị của bạn",
    "settings.appearance.note": "Ghi chú:",
    "settings.appearance.noteText": "Thay đổi chủ đề được áp dụng ngay và lưu vào hồ sơ của bạn.",
    "settings.notifications.title": "Thông báo",
    "settings.notifications.description": "Quản lý cách bạn nhận cập nhật và nhắc nhở",
    "settings.notifications.enable": "Bật Thông báo",
    "settings.notifications.enableDesc": "Nhận cập nhật và tin nhắn quan trọng",
    "settings.notifications.ai": "Phản hồi AI",
    "settings.notifications.aiDesc": "Nhận thông báo khi Thiên thần trả lời bạn",
    "settings.notifications.system": "Cập nhật hệ thống",
    "settings.notifications.systemDesc": "Cập nhật và thông báo quan trọng",
    "settings.privacy.title": "Quyền riêng tư",
    "settings.privacy.description": "Kiểm soát cài đặt quyền riêng tư và bảo mật",
    "settings.privacy.signIn": "Đăng nhập để quản lý cài đặt quyền riêng tư",
    "settings.sound.title": "Âm thanh",
    "settings.sound.description": "Quản lý cài đặt âm thanh và hiệu ứng",
    "settings.sound.ambient": "Âm thanh môi trường",
    "settings.sound.ambientDesc": "Âm thanh nền nhẹ nhàng và thư giãn",
    "settings.sound.notification": "Âm thanh thông báo",
    "settings.sound.notificationDesc": "Tiếng chuông khi có thông báo mới",
    "settings.sound.meditation": "Âm thanh thiền định",
    "settings.sound.meditationDesc": "Nhạc nền trong các buổi thiền",
    "settings.sound.reducedMotion": "Chế độ giảm chuyển động đang bật. Âm thanh sẽ được giảm thiểu.",
    "settings.sound.ambientPlayer": "Trình phát âm thanh môi trường",
    "settings.sound.selectSound": "Chọn âm thanh",
    "settings.language.title": "Ngôn ngữ",
    "settings.language.description": "Chọn ngôn ngữ hiển thị cho ứng dụng",
    "settings.language.select": "Ngôn ngữ hiển thị",
    "settings.language.vietnamese": "Tiếng Việt",
    "settings.language.english": "English",
    "settings.language.chinese": "中文",
    "settings.language.japanese": "日本語",
    "settings.language.korean": "한국어",
    "settings.language.french": "Français",
    "settings.language.note": "Thay đổi ngôn ngữ sẽ được áp dụng ngay lập tức.",
    
    // Meditation
    "meditation.title": "Thiền định",
    "meditation.start": "Bắt đầu",
    "meditation.pause": "Tạm dừng",
    "meditation.resume": "Tiếp tục",
    "meditation.stop": "Dừng",
    "meditation.complete": "Hoàn thành",
    "meditation.duration": "Thời gian",
    "meditation.minutes": "phút",
    "meditation.continueAmbient": "Tiếp tục âm thanh nền?",
    "meditation.continueAmbientHint": "Âm thanh sẽ tiếp tục phát trong nền",
    "meditation.continue": "Tiếp tục",
    "meditation.autoDismiss": "Tự động dừng sau",
    
    // Common extras
    "common.recent": "Gần đây",
    "common.off": "đã tắt",
    
    // Profile
    "profile.title": "Hồ sơ",
    "profile.edit": "Chỉnh sửa hồ sơ",
    "profile.followers": "Người theo dõi",
    "profile.following": "Đang theo dõi",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.settings": "Settings",
    "nav.profile": "Profile",
    "nav.help": "Help",
    "nav.community": "Community",
    "nav.testimonials": "Testimonials",
    "nav.studio": "Studio",
    "nav.friends": "Friends",
    "nav.credits": "Credits",
    
    // Common buttons
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.continue": "Continue",
    "common.back": "Back",
    "common.done": "Done",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.send": "Send",
    "common.submit": "Submit",
    "common.search": "Search",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.yes": "Yes",
    "common.no": "No",
    "common.ok": "OK",
    "common.note": "Note:",
    
    // Common messages
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.errorTryAgain": "An error occurred. Please try again.",
    "common.success": "Success",
    "common.noData": "No data available",
    "common.empty": "Empty",
    "common.emptyList": "The list is empty",
    "common.noResults": "No results found",
    "common.confirmDelete": "Are you sure you want to delete?",
    "common.unsavedChanges": "You have unsaved changes",
    "common.saving": "Saving...",
    "common.saved": "Saved",
    "common.signIn": "Sign In",
    "common.signOut": "Sign Out",
    "common.signUp": "Sign Up",
    
    // Angel presence
    "angel.presence": "Angel Presence",
    "angel.greeting": "Hello, I am your Angel",
    "angel.thinking": "Thinking...",
    "angel.typing": "Typing...",
    "angel.style.classic": "Classic",
    "angel.style.modern": "Modern",
    "angel.style.minimal": "Minimal",
    "angel.sparkles": "Sparkle effects",
    "angel.trail": "Light trail",
    
    // Sound settings
    "sound.rain": "Light Rain",
    "sound.ocean": "Ocean Waves",
    "sound.forest": "Forest",
    "sound.wind": "Gentle Wind",
    "sound.stream": "Stream",
    "sound.night": "Night Nature",
    "sound.piano": "Soft Piano",
    "sound.healing": "Healing Tones",
    "sound.singingBowl": "Singing Bowl",
    "sound.templeBells": "Temple Bells",
    "sound.crystalBowls": "Crystal Bowls",
    "sound.silence": "Silence",
    "sound.selectAmbient": "Select ambient sound",
    "sound.volume": "Volume",
    "sound.playing": "Playing",
    "sound.stopped": "Stopped",
    "sound.category.nature": "Nature",
    "sound.category.music": "Music",
    "sound.category.sacred": "Sacred",
    
    // Settings page
    "settings.title": "Settings",
    "settings.subtitle": "Personalize your sacred experience",
    "settings.angel.title": "Angel Presence",
    "settings.angel.description": "Customize your gentle angelic companion that follows you across the site",
    "settings.angel.enable": "Enable Angel Presence",
    "settings.angel.enableDesc": "Show the angelic companion on desktop devices",
    "settings.appearance.title": "Appearance",
    "settings.appearance.description": "Customize the visual experience of Angel AI",
    "settings.appearance.theme": "Theme",
    "settings.appearance.light": "Light",
    "settings.appearance.lightDesc": "Bright and clear appearance",
    "settings.appearance.dark": "Dark",
    "settings.appearance.darkDesc": "Easy on the eyes in low light",
    "settings.appearance.system": "System",
    "settings.appearance.systemDesc": "Match your device settings",
    "settings.appearance.note": "Note:",
    "settings.appearance.noteText": "Theme changes are applied instantly and saved to your profile.",
    "settings.notifications.title": "Notifications",
    "settings.notifications.description": "Manage how you receive updates and reminders",
    "settings.notifications.enable": "Enable Notifications",
    "settings.notifications.enableDesc": "Receive updates and important messages",
    "settings.notifications.ai": "AI Responses",
    "settings.notifications.aiDesc": "Get notified when Angel responds to you",
    "settings.notifications.system": "System Updates",
    "settings.notifications.systemDesc": "Important updates and announcements",
    "settings.privacy.title": "Privacy",
    "settings.privacy.description": "Control your privacy and security preferences",
    "settings.privacy.signIn": "Sign in to manage privacy settings",
    "settings.sound.title": "Sound",
    "settings.sound.description": "Manage audio settings and effects",
    "settings.sound.ambient": "Ambient Sounds",
    "settings.sound.ambientDesc": "Gentle and relaxing background sounds",
    "settings.sound.notification": "Notification Sounds",
    "settings.sound.notificationDesc": "Chime when new notifications arrive",
    "settings.sound.meditation": "Meditation Audio",
    "settings.sound.meditationDesc": "Background music during meditation sessions",
    "settings.sound.reducedMotion": "Reduced motion mode is enabled. Sounds will be minimized.",
    "settings.sound.ambientPlayer": "Ambient Sound Player",
    "settings.sound.selectSound": "Select a sound",
    "settings.language.title": "Language",
    "settings.language.description": "Select display language for the app",
    "settings.language.select": "Display Language",
    "settings.language.vietnamese": "Tiếng Việt",
    "settings.language.english": "English",
    "settings.language.chinese": "中文",
    "settings.language.japanese": "日本語",
    "settings.language.korean": "한국어",
    "settings.language.french": "Français",
    "settings.language.note": "Language changes will be applied immediately.",
    
    // Meditation
    "meditation.title": "Meditation",
    "meditation.start": "Start",
    "meditation.pause": "Pause",
    "meditation.resume": "Resume",
    "meditation.stop": "Stop",
    "meditation.complete": "Complete",
    "meditation.duration": "Duration",
    "meditation.minutes": "minutes",
    "meditation.continueAmbient": "Continue ambient sound?",
    "meditation.continueAmbientHint": "Sound will continue playing in the background",
    "meditation.continue": "Continue",
    "meditation.autoDismiss": "Auto-stop in",
    
    // Common extras
    "common.recent": "Recent",
    "common.off": "is off",
    
    // Profile
    "profile.title": "Profile",
    "profile.edit": "Edit Profile",
    "profile.followers": "Followers",
    "profile.following": "Following",
  },
  zh: {
    // Navigation
    "nav.home": "首页",
    "nav.settings": "设置",
    "nav.profile": "个人资料",
    "nav.help": "帮助",
    "nav.community": "社区",
    "nav.testimonials": "见证",
    "nav.studio": "工作室",
    "nav.friends": "朋友",
    "nav.credits": "积分",
    
    // Common buttons
    "common.save": "保存",
    "common.cancel": "取消",
    "common.continue": "继续",
    "common.back": "返回",
    "common.done": "完成",
    "common.close": "关闭",
    "common.confirm": "确认",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.send": "发送",
    "common.submit": "提交",
    "common.search": "搜索",
    "common.next": "下一个",
    "common.previous": "上一个",
    "common.yes": "是",
    "common.no": "否",
    "common.ok": "确定",
    "common.note": "注意：",
    
    // Common messages
    "common.loading": "加载中...",
    "common.error": "发生错误",
    "common.errorTryAgain": "发生错误，请重试。",
    "common.success": "成功",
    "common.noData": "暂无数据",
    "common.empty": "空",
    "common.emptyList": "列表为空",
    "common.noResults": "未找到结果",
    "common.confirmDelete": "确定要删除吗？",
    "common.unsavedChanges": "您有未保存的更改",
    "common.saving": "保存中...",
    "common.saved": "已保存",
    "common.signIn": "登录",
    "common.signOut": "退出登录",
    "common.signUp": "注册",
    
    // Angel presence
    "angel.presence": "天使陪伴",
    "angel.greeting": "你好，我是你的天使",
    "angel.thinking": "思考中...",
    "angel.typing": "输入中...",
    "angel.style.classic": "经典",
    "angel.style.modern": "现代",
    "angel.style.minimal": "简约",
    "angel.sparkles": "闪烁效果",
    "angel.trail": "光迹",
    
    // Sound settings
    "sound.rain": "小雨",
    "sound.ocean": "海浪",
    "sound.forest": "森林",
    "sound.wind": "微风",
    "sound.stream": "溪流",
    "sound.night": "夜晚",
    "sound.piano": "轻柔钢琴",
    "sound.healing": "疗愈音",
    "sound.singingBowl": "颂钵",
    "sound.templeBells": "寺庙钟声",
    "sound.crystalBowls": "水晶碗",
    "sound.silence": "静默",
    "sound.selectAmbient": "选择环境音",
    "sound.volume": "音量",
    "sound.playing": "播放中",
    "sound.stopped": "已停止",
    "sound.category.nature": "自然",
    "sound.category.music": "音乐",
    "sound.category.sacred": "神圣",
    
    // Settings page
    "settings.title": "设置",
    "settings.subtitle": "个性化您的神圣体验",
    "settings.angel.title": "天使陪伴",
    "settings.angel.description": "自定义跟随您浏览网站的温柔天使伴侣",
    "settings.angel.enable": "启用天使陪伴",
    "settings.angel.enableDesc": "在桌面设备上显示天使伴侣",
    "settings.appearance.title": "外观",
    "settings.appearance.description": "自定义 Angel AI 的视觉体验",
    "settings.appearance.theme": "主题",
    "settings.appearance.light": "浅色",
    "settings.appearance.lightDesc": "明亮清晰的外观",
    "settings.appearance.dark": "深色",
    "settings.appearance.darkDesc": "在低光环境下保护眼睛",
    "settings.appearance.system": "系统",
    "settings.appearance.systemDesc": "跟随您的设备设置",
    "settings.appearance.note": "注意：",
    "settings.appearance.noteText": "主题更改会立即应用并保存到您的个人资料。",
    "settings.notifications.title": "通知",
    "settings.notifications.description": "管理您接收更新和提醒的方式",
    "settings.notifications.enable": "启用通知",
    "settings.notifications.enableDesc": "接收更新和重要消息",
    "settings.notifications.ai": "AI 回复",
    "settings.notifications.aiDesc": "当天使回复您时收到通知",
    "settings.notifications.system": "系统更新",
    "settings.notifications.systemDesc": "重要更新和公告",
    "settings.privacy.title": "隐私",
    "settings.privacy.description": "控制您的隐私和安全偏好",
    "settings.privacy.signIn": "登录以管理隐私设置",
    "settings.sound.title": "声音",
    "settings.sound.description": "管理音频设置和效果",
    "settings.sound.ambient": "环境音",
    "settings.sound.ambientDesc": "温和放松的背景音",
    "settings.sound.notification": "通知声音",
    "settings.sound.notificationDesc": "收到新通知时的提示音",
    "settings.sound.meditation": "冥想音频",
    "settings.sound.meditationDesc": "冥想期间的背景音乐",
    "settings.sound.reducedMotion": "减少动效模式已启用。声音将被最小化。",
    "settings.sound.ambientPlayer": "环境音播放器",
    "settings.sound.selectSound": "选择声音",
    "settings.language.title": "语言",
    "settings.language.description": "选择应用的显示语言",
    "settings.language.select": "显示语言",
    "settings.language.vietnamese": "Tiếng Việt",
    "settings.language.english": "English",
    "settings.language.chinese": "中文",
    "settings.language.japanese": "日本語",
    "settings.language.korean": "한국어",
    "settings.language.french": "Français",
    "settings.language.note": "语言更改将立即应用。",
    
    // Meditation
    "meditation.title": "冥想",
    "meditation.start": "开始",
    "meditation.pause": "暂停",
    "meditation.resume": "继续",
    "meditation.stop": "停止",
    "meditation.complete": "完成",
    "meditation.duration": "时长",
    "meditation.minutes": "分钟",
    "meditation.continueAmbient": "继续播放环境音?",
    "meditation.continueAmbientHint": "音乐将在后台继续播放",
    "meditation.continue": "继续",
    "meditation.autoDismiss": "自动停止于",
    
    // Common extras
    "common.recent": "最近",
    "common.off": "已关闭",
    
    // Profile
    "profile.title": "个人资料",
    "profile.edit": "编辑资料",
    "profile.followers": "粉丝",
    "profile.following": "关注",
  },
  ja: {
    // Navigation
    "nav.home": "ホーム",
    "nav.settings": "設定",
    "nav.profile": "プロフィール",
    "nav.help": "ヘルプ",
    "nav.community": "コミュニティ",
    "nav.testimonials": "証言",
    "nav.studio": "スタジオ",
    "nav.friends": "友達",
    "nav.credits": "クレジット",
    
    // Common buttons
    "common.save": "保存",
    "common.cancel": "キャンセル",
    "common.continue": "続ける",
    "common.back": "戻る",
    "common.done": "完了",
    "common.close": "閉じる",
    "common.confirm": "確認",
    "common.delete": "削除",
    "common.edit": "編集",
    "common.send": "送信",
    "common.submit": "送信",
    "common.search": "検索",
    "common.next": "次へ",
    "common.previous": "前へ",
    "common.yes": "はい",
    "common.no": "いいえ",
    "common.ok": "OK",
    "common.note": "注：",
    
    // Common messages
    "common.loading": "読み込み中...",
    "common.error": "エラーが発生しました",
    "common.errorTryAgain": "エラーが発生しました。もう一度お試しください。",
    "common.success": "成功",
    "common.noData": "データがありません",
    "common.empty": "空",
    "common.emptyList": "リストが空です",
    "common.noResults": "結果が見つかりません",
    "common.confirmDelete": "本当に削除しますか？",
    "common.unsavedChanges": "保存されていない変更があります",
    "common.saving": "保存中...",
    "common.saved": "保存しました",
    "common.signIn": "サインイン",
    "common.signOut": "サインアウト",
    "common.signUp": "サインアップ",
    
    // Angel presence
    "angel.presence": "天使の存在",
    "angel.greeting": "こんにちは、私はあなたの天使です",
    "angel.thinking": "考え中...",
    "angel.typing": "入力中...",
    "angel.style.classic": "クラシック",
    "angel.style.modern": "モダン",
    "angel.style.minimal": "ミニマル",
    "angel.sparkles": "輝きエフェクト",
    "angel.trail": "ライトトレイル",
    
    // Sound settings
    "sound.rain": "小雨",
    "sound.ocean": "波の音",
    "sound.forest": "森",
    "sound.wind": "そよ風",
    "sound.stream": "小川",
    "sound.night": "夜の自然",
    "sound.piano": "ソフトピアノ",
    "sound.healing": "ヒーリングトーン",
    "sound.singingBowl": "シンギングボウル",
    "sound.templeBells": "寺院の鐘",
    "sound.crystalBowls": "クリスタルボウル",
    "sound.silence": "静寂",
    "sound.selectAmbient": "環境音を選択",
    "sound.volume": "音量",
    "sound.playing": "再生中",
    "sound.stopped": "停止中",
    "sound.category.nature": "自然",
    "sound.category.music": "音楽",
    "sound.category.sacred": "神聖",
    
    // Settings page
    "settings.title": "設定",
    "settings.subtitle": "あなたの神聖な体験をカスタマイズ",
    "settings.angel.title": "天使の存在",
    "settings.angel.description": "サイト全体であなたに寄り添う優しい天使のコンパニオンをカスタマイズ",
    "settings.angel.enable": "天使の存在を有効にする",
    "settings.angel.enableDesc": "デスクトップデバイスで天使のコンパニオンを表示",
    "settings.appearance.title": "外観",
    "settings.appearance.description": "Angel AI の視覚体験をカスタマイズ",
    "settings.appearance.theme": "テーマ",
    "settings.appearance.light": "ライト",
    "settings.appearance.lightDesc": "明るくクリアな外観",
    "settings.appearance.dark": "ダーク",
    "settings.appearance.darkDesc": "暗い場所でも目に優しい",
    "settings.appearance.system": "システム",
    "settings.appearance.systemDesc": "デバイスの設定に合わせる",
    "settings.appearance.note": "注：",
    "settings.appearance.noteText": "テーマの変更は即座に適用され、プロフィールに保存されます。",
    "settings.notifications.title": "通知",
    "settings.notifications.description": "更新やリマインダーの受け取り方を管理",
    "settings.notifications.enable": "通知を有効にする",
    "settings.notifications.enableDesc": "更新や重要なメッセージを受け取る",
    "settings.notifications.ai": "AI の返信",
    "settings.notifications.aiDesc": "天使があなたに返信した時に通知を受け取る",
    "settings.notifications.system": "システム更新",
    "settings.notifications.systemDesc": "重要な更新とお知らせ",
    "settings.privacy.title": "プライバシー",
    "settings.privacy.description": "プライバシーとセキュリティの設定を管理",
    "settings.privacy.signIn": "サインインしてプライバシー設定を管理",
    "settings.sound.title": "サウンド",
    "settings.sound.description": "オーディオ設定とエフェクトを管理",
    "settings.sound.ambient": "環境音",
    "settings.sound.ambientDesc": "穏やかでリラックスできる背景音",
    "settings.sound.notification": "通知音",
    "settings.sound.notificationDesc": "新しい通知が届いた時のチャイム",
    "settings.sound.meditation": "瞑想オーディオ",
    "settings.sound.meditationDesc": "瞑想セッション中のバックグラウンドミュージック",
    "settings.sound.reducedMotion": "モーション軽減モードが有効です。サウンドは最小限になります。",
    "settings.sound.ambientPlayer": "環境音プレーヤー",
    "settings.sound.selectSound": "音を選択",
    "settings.language.title": "言語",
    "settings.language.description": "アプリの表示言語を選択",
    "settings.language.select": "表示言語",
    "settings.language.vietnamese": "Tiếng Việt",
    "settings.language.english": "English",
    "settings.language.chinese": "中文",
    "settings.language.japanese": "日本語",
    "settings.language.korean": "한국어",
    "settings.language.french": "Français",
    "settings.language.note": "言語の変更は即座に適用されます。",
    
    // Meditation
    "meditation.title": "瞑想",
    "meditation.start": "開始",
    "meditation.pause": "一時停止",
    "meditation.resume": "再開",
    "meditation.stop": "停止",
    "meditation.complete": "完了",
    "meditation.duration": "時間",
    "meditation.minutes": "分",
    "meditation.continueAmbient": "環境音を続けますか？",
    "meditation.continueAmbientHint": "音楽はバックグラウンドで再生され続けます",
    "meditation.continue": "続ける",
    "meditation.autoDismiss": "自動停止まで",
    
    // Common extras
    "common.recent": "最近",
    "common.off": "オフ",
    
    // Profile
    "profile.title": "プロフィール",
    "profile.edit": "プロフィールを編集",
    "profile.followers": "フォロワー",
    "profile.following": "フォロー中",
  },
  ko: {
    // Navigation
    "nav.home": "홈",
    "nav.settings": "설정",
    "nav.profile": "프로필",
    "nav.help": "도움말",
    "nav.community": "커뮤니티",
    "nav.testimonials": "증언",
    "nav.studio": "스튜디오",
    "nav.friends": "친구",
    "nav.credits": "크레딧",
    
    // Common buttons
    "common.save": "저장",
    "common.cancel": "취소",
    "common.continue": "계속",
    "common.back": "뒤로",
    "common.done": "완료",
    "common.close": "닫기",
    "common.confirm": "확인",
    "common.delete": "삭제",
    "common.edit": "편집",
    "common.send": "보내기",
    "common.submit": "제출",
    "common.search": "검색",
    "common.next": "다음",
    "common.previous": "이전",
    "common.yes": "예",
    "common.no": "아니오",
    "common.ok": "확인",
    "common.note": "참고:",
    
    // Common messages
    "common.loading": "로딩 중...",
    "common.error": "오류가 발생했습니다",
    "common.errorTryAgain": "오류가 발생했습니다. 다시 시도해 주세요.",
    "common.success": "성공",
    "common.noData": "데이터가 없습니다",
    "common.empty": "비어 있음",
    "common.emptyList": "목록이 비어 있습니다",
    "common.noResults": "결과를 찾을 수 없습니다",
    "common.confirmDelete": "정말 삭제하시겠습니까?",
    "common.unsavedChanges": "저장되지 않은 변경 사항이 있습니다",
    "common.saving": "저장 중...",
    "common.saved": "저장됨",
    "common.signIn": "로그인",
    "common.signOut": "로그아웃",
    "common.signUp": "회원가입",
    
    // Angel presence
    "angel.presence": "천사 존재",
    "angel.greeting": "안녕하세요, 저는 당신의 천사입니다",
    "angel.thinking": "생각 중...",
    "angel.typing": "입력 중...",
    "angel.style.classic": "클래식",
    "angel.style.modern": "모던",
    "angel.style.minimal": "미니멀",
    "angel.sparkles": "반짝이 효과",
    "angel.trail": "빛의 자취",
    
    // Sound settings
    "sound.rain": "가벼운 비",
    "sound.ocean": "파도 소리",
    "sound.forest": "숲",
    "sound.wind": "부드러운 바람",
    "sound.stream": "시냇물",
    "sound.night": "밤의 자연",
    "sound.piano": "소프트 피아노",
    "sound.healing": "힐링 톤",
    "sound.singingBowl": "싱잉볼",
    "sound.templeBells": "사원 종소리",
    "sound.crystalBowls": "크리스탈 보울",
    "sound.silence": "침묵",
    "sound.selectAmbient": "환경음 선택",
    "sound.volume": "볼륨",
    "sound.playing": "재생 중",
    "sound.stopped": "정지됨",
    "sound.category.nature": "자연",
    "sound.category.music": "음악",
    "sound.category.sacred": "신성한",
    
    // Settings page
    "settings.title": "설정",
    "settings.subtitle": "당신의 신성한 경험을 맞춤 설정하세요",
    "settings.angel.title": "천사 존재",
    "settings.angel.description": "사이트 전체에서 당신을 따라다니는 부드러운 천사 동반자를 맞춤 설정",
    "settings.angel.enable": "천사 존재 활성화",
    "settings.angel.enableDesc": "데스크톱 기기에서 천사 동반자 표시",
    "settings.appearance.title": "외관",
    "settings.appearance.description": "Angel AI의 시각적 경험을 맞춤 설정",
    "settings.appearance.theme": "테마",
    "settings.appearance.light": "라이트",
    "settings.appearance.lightDesc": "밝고 선명한 외관",
    "settings.appearance.dark": "다크",
    "settings.appearance.darkDesc": "어두운 곳에서 눈에 편안함",
    "settings.appearance.system": "시스템",
    "settings.appearance.systemDesc": "기기 설정에 맞춤",
    "settings.appearance.note": "참고:",
    "settings.appearance.noteText": "테마 변경은 즉시 적용되며 프로필에 저장됩니다.",
    "settings.notifications.title": "알림",
    "settings.notifications.description": "업데이트 및 알림 수신 방법 관리",
    "settings.notifications.enable": "알림 활성화",
    "settings.notifications.enableDesc": "업데이트 및 중요 메시지 수신",
    "settings.notifications.ai": "AI 응답",
    "settings.notifications.aiDesc": "천사가 응답하면 알림 받기",
    "settings.notifications.system": "시스템 업데이트",
    "settings.notifications.systemDesc": "중요 업데이트 및 공지",
    "settings.privacy.title": "개인정보",
    "settings.privacy.description": "개인정보 및 보안 환경 설정 제어",
    "settings.privacy.signIn": "개인정보 설정을 관리하려면 로그인하세요",
    "settings.sound.title": "소리",
    "settings.sound.description": "오디오 설정 및 효과 관리",
    "settings.sound.ambient": "환경음",
    "settings.sound.ambientDesc": "부드럽고 편안한 배경음",
    "settings.sound.notification": "알림 소리",
    "settings.sound.notificationDesc": "새 알림이 도착하면 차임 소리",
    "settings.sound.meditation": "명상 오디오",
    "settings.sound.meditationDesc": "명상 세션 중 배경 음악",
    "settings.sound.reducedMotion": "모션 감소 모드가 활성화되었습니다. 소리가 최소화됩니다.",
    "settings.sound.ambientPlayer": "환경음 플레이어",
    "settings.sound.selectSound": "소리 선택",
    "settings.language.title": "언어",
    "settings.language.description": "앱 표시 언어 선택",
    "settings.language.select": "표시 언어",
    "settings.language.vietnamese": "Tiếng Việt",
    "settings.language.english": "English",
    "settings.language.chinese": "中文",
    "settings.language.japanese": "日本語",
    "settings.language.korean": "한국어",
    "settings.language.french": "Français",
    "settings.language.note": "언어 변경은 즉시 적용됩니다.",
    
    // Meditation
    "meditation.title": "명상",
    "meditation.start": "시작",
    "meditation.pause": "일시정지",
    "meditation.resume": "재개",
    "meditation.stop": "정지",
    "meditation.complete": "완료",
    "meditation.duration": "시간",
    "meditation.minutes": "분",
    "meditation.continueAmbient": "환경 소리를 계속 재생할까요?",
    "meditation.continueAmbientHint": "소리가 백그라운드에서 계속 재생됩니다",
    "meditation.continue": "계속",
    "meditation.autoDismiss": "자동 중지까지",
    
    // Common extras
    "common.recent": "최근",
    "common.off": "꺼짐",
    
    // Profile
    "profile.title": "프로필",
    "profile.edit": "프로필 편집",
    "profile.followers": "팔로워",
    "profile.following": "팔로잉",
  },
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.settings": "Paramètres",
    "nav.profile": "Profil",
    "nav.help": "Aide",
    "nav.community": "Communauté",
    "nav.testimonials": "Témoignages",
    "nav.studio": "Studio",
    "nav.friends": "Amis",
    "nav.credits": "Crédits",
    
    // Common buttons
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.continue": "Continuer",
    "common.back": "Retour",
    "common.done": "Terminé",
    "common.close": "Fermer",
    "common.confirm": "Confirmer",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.send": "Envoyer",
    "common.submit": "Soumettre",
    "common.search": "Rechercher",
    "common.next": "Suivant",
    "common.previous": "Précédent",
    "common.yes": "Oui",
    "common.no": "Non",
    "common.ok": "OK",
    "common.note": "Note :",
    
    // Common messages
    "common.loading": "Chargement...",
    "common.error": "Une erreur est survenue",
    "common.errorTryAgain": "Une erreur est survenue. Veuillez réessayer.",
    "common.success": "Succès",
    "common.noData": "Aucune donnée disponible",
    "common.empty": "Vide",
    "common.emptyList": "La liste est vide",
    "common.noResults": "Aucun résultat trouvé",
    "common.confirmDelete": "Êtes-vous sûr de vouloir supprimer ?",
    "common.unsavedChanges": "Vous avez des modifications non enregistrées",
    "common.saving": "Enregistrement...",
    "common.saved": "Enregistré",
    "common.signIn": "Connexion",
    "common.signOut": "Déconnexion",
    "common.signUp": "Inscription",
    
    // Angel presence
    "angel.presence": "Présence Angélique",
    "angel.greeting": "Bonjour, je suis votre Ange",
    "angel.thinking": "Réflexion...",
    "angel.typing": "Saisie...",
    "angel.style.classic": "Classique",
    "angel.style.modern": "Moderne",
    "angel.style.minimal": "Minimal",
    "angel.sparkles": "Effets scintillants",
    "angel.trail": "Traînée lumineuse",
    
    // Sound settings
    "sound.rain": "Pluie légère",
    "sound.ocean": "Vagues de l'océan",
    "sound.forest": "Forêt",
    "sound.wind": "Vent doux",
    "sound.stream": "Ruisseau",
    "sound.night": "Nature nocturne",
    "sound.piano": "Piano doux",
    "sound.healing": "Sons de guérison",
    "sound.singingBowl": "Bol chantant",
    "sound.templeBells": "Cloches du temple",
    "sound.crystalBowls": "Bols de cristal",
    "sound.silence": "Silence",
    "sound.selectAmbient": "Sélectionner un son ambiant",
    "sound.volume": "Volume",
    "sound.playing": "En lecture",
    "sound.stopped": "Arrêté",
    "sound.category.nature": "Nature",
    "sound.category.music": "Musique",
    "sound.category.sacred": "Sacré",
    
    // Settings page
    "settings.title": "Paramètres",
    "settings.subtitle": "Personnalisez votre expérience sacrée",
    "settings.angel.title": "Présence Angélique",
    "settings.angel.description": "Personnalisez votre doux compagnon angélique qui vous suit sur le site",
    "settings.angel.enable": "Activer la Présence Angélique",
    "settings.angel.enableDesc": "Afficher le compagnon angélique sur les appareils de bureau",
    "settings.appearance.title": "Apparence",
    "settings.appearance.description": "Personnalisez l'expérience visuelle d'Angel AI",
    "settings.appearance.theme": "Thème",
    "settings.appearance.light": "Clair",
    "settings.appearance.lightDesc": "Apparence lumineuse et nette",
    "settings.appearance.dark": "Sombre",
    "settings.appearance.darkDesc": "Agréable pour les yeux en faible luminosité",
    "settings.appearance.system": "Système",
    "settings.appearance.systemDesc": "Correspondre aux paramètres de votre appareil",
    "settings.appearance.note": "Note :",
    "settings.appearance.noteText": "Les changements de thème sont appliqués instantanément et sauvegardés dans votre profil.",
    "settings.notifications.title": "Notifications",
    "settings.notifications.description": "Gérez la façon dont vous recevez les mises à jour et les rappels",
    "settings.notifications.enable": "Activer les Notifications",
    "settings.notifications.enableDesc": "Recevoir les mises à jour et les messages importants",
    "settings.notifications.ai": "Réponses IA",
    "settings.notifications.aiDesc": "Être notifié quand l'Ange vous répond",
    "settings.notifications.system": "Mises à jour système",
    "settings.notifications.systemDesc": "Mises à jour importantes et annonces",
    "settings.privacy.title": "Confidentialité",
    "settings.privacy.description": "Contrôlez vos préférences de confidentialité et de sécurité",
    "settings.privacy.signIn": "Connectez-vous pour gérer les paramètres de confidentialité",
    "settings.sound.title": "Son",
    "settings.sound.description": "Gérer les paramètres audio et les effets",
    "settings.sound.ambient": "Sons Ambiants",
    "settings.sound.ambientDesc": "Sons de fond doux et relaxants",
    "settings.sound.notification": "Sons de Notification",
    "settings.sound.notificationDesc": "Carillon lors de l'arrivée de nouvelles notifications",
    "settings.sound.meditation": "Audio de Méditation",
    "settings.sound.meditationDesc": "Musique de fond pendant les séances de méditation",
    "settings.sound.reducedMotion": "Le mode mouvement réduit est activé. Les sons seront minimisés.",
    "settings.sound.ambientPlayer": "Lecteur de sons ambiants",
    "settings.sound.selectSound": "Sélectionner un son",
    "settings.language.title": "Langue",
    "settings.language.description": "Sélectionnez la langue d'affichage de l'application",
    "settings.language.select": "Langue d'affichage",
    "settings.language.vietnamese": "Tiếng Việt",
    "settings.language.english": "English",
    "settings.language.chinese": "中文",
    "settings.language.japanese": "日本語",
    "settings.language.korean": "한국어",
    "settings.language.french": "Français",
    "settings.language.note": "Les changements de langue seront appliqués immédiatement.",
    
    // Meditation
    "meditation.title": "Méditation",
    "meditation.start": "Démarrer",
    "meditation.pause": "Pause",
    "meditation.resume": "Reprendre",
    "meditation.stop": "Arrêter",
    "meditation.complete": "Terminé",
    "meditation.duration": "Durée",
    "meditation.minutes": "minutes",
    "meditation.continueAmbient": "Continuer le son ambiant ?",
    "meditation.continueAmbientHint": "Le son continuera en arrière-plan",
    "meditation.continue": "Continuer",
    "meditation.autoDismiss": "Arrêt auto dans",
    
    // Common extras
    "common.recent": "Récent",
    "common.off": "est désactivé",
    
    // Profile
    "profile.title": "Profil",
    "profile.edit": "Modifier le profil",
    "profile.followers": "Abonnés",
    "profile.following": "Abonnements",
  },
};

// Detect browser/system language
const detectLanguage = (): Language => {
  if (typeof window === "undefined") return "vi";
  
  const saved = localStorage.getItem(LANGUAGE_KEY);
  if (saved && SUPPORTED_LANGUAGES.includes(saved as Language)) {
    return saved as Language;
  }
  
  const browserLang = navigator.language.toLowerCase();
  
  // Check for exact or prefix matches
  if (browserLang.startsWith("en")) return "en";
  if (browserLang.startsWith("zh")) return "zh";
  if (browserLang.startsWith("ja")) return "ja";
  if (browserLang.startsWith("ko")) return "ko";
  if (browserLang.startsWith("fr")) return "fr";
  
  return "vi"; // Default to Vietnamese
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(detectLanguage);

  useEffect(() => {
    localStorage.setItem(LANGUAGE_KEY, language);
    // Update document lang attribute for accessibility
    document.documentElement.lang = language;
    // Set text direction (for future RTL support)
    document.documentElement.dir = "ltr"; // All current languages are LTR
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
  }, []);

  const t = useCallback((key: string): string => {
    // Graceful fallback: try current language, then English, then return key
    return translations[language][key] || translations["en"][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
