/**
 * Angel Presence Type Definitions
 */

export type AngelStyle = 'classic' | 'cherub' | 'seraph' | 'guardian' | 'joy' | 'peace' | 'healing' | 'fairy' | 'fairy-blue' | 'fairy-red' | 'fairy-pink' | 'fairy-mint' | 'fairy-gold' | 'fairy-yellow' | 'fairy-green' | 'fairy-tinker' | 'fairy-cute' | 'fairy-star' | 'fairy-leaf' | 'fairy-sunny' | 'fairy-butterfly' | 'fairy-spring' | 'fairy-heart' | 'fairy-love' | 'fairy-lavender' | 'fairy-rosemary' | 'fairy-butterfly-gold' | 'fairy-sunflower' | 'fairy-peach' | 'fairy-lime' | 'fairy-ruby' | 'fairy-ocean' | 'fairy-sakura' | 'fairy-cherry-blossom' | 'fairy-doll' | 'fairy-rainbow' | 'fairy-colorful' | 'fairy-pencil' | 'fairy-teal' | 'fairy-violet' | 'fairy-strawberry' | 'fairy-mint-star' | 'fairy-pink-star' | 'fairy-rose-dress' | 'fairy-golden-sit' | 'fairy-nature-wings' | 'fairy-butterfly-colorful' | 'fairy-rainbow-wings' | 'fairy-galaxy' | 'fairy-purple-flower' | 'fairy-violet-bloom' | 'fairy-easter' | 'fairy-prayer' | 'fairy-tinkerbell' | 'fairy-video' | 'celestial-video' | 'starlight-seraph' | 'aurora-guardian' | 'nebula-messenger' | 'grok-angel-1' | 'grok-angel-2' | 'grok-angel-3' | 'grok-angel-4' | 'grok-angel-5' | 'grok-angel-6' | 'grok-angel-7' | 'grok-angel-8';

export type AngelColor = 'white' | 'gold' | 'blue' | 'pink' | 'green' | 'purple';

export interface AngelColorConfig {
  id: AngelColor;
  name: string;
  hsl: string;
  glowColor: string;
}

export interface AngelAnimationConfig {
  floatDuration: number;      // seconds - main float cycle
  floatAmplitude: number;     // pixels - vertical float distance
  flapDuration?: number;      // seconds - wing flap (if applicable)
  followEasing: number;       // 0-1 - how smoothly it follows cursor
  sparkleIntensity: number;   // 0-1 - particle spawn rate multiplier
  trailIntensity: number;     // 0-1 - trail opacity/length multiplier
  bouncy?: boolean;           // adds micro-bounce effect
  pulseGlow?: boolean;        // adds breathing glow effect
}

export type VideoQuality = 'high' | 'performance';

export interface VideoSources {
  webmHighSrc?: string;    // WebM with alpha - high quality
  webmPerfSrc?: string;    // WebM with alpha - performance optimized
  mp4HighSrc: string;      // MP4 fallback - high quality (required)
  mp4PerfSrc?: string;     // MP4 fallback - performance optimized
  posterSrc?: string;      // Thumbnail for selector
}

export interface AngelStyleConfig {
  id: AngelStyle;
  name: string;
  description: string;
  glowIntensity: number; // 0-1
  glowColor: string;
  scale: number;
  animation: AngelAnimationConfig;
  isVideo?: boolean;
  videoSources?: VideoSources;
}

export interface SparkleParticle {
  id: string;
  x: number;
  y: number;
  size: number;
  opacity: number;
  createdAt: number;
}

export interface TrailPoint {
  id: string;
  x: number;
  y: number;
  opacity: number;
  createdAt: number;
}

export interface AngelPresenceSettings {
  enabled: boolean;
  style: AngelStyle;
  color: AngelColor;
  sparklesEnabled: boolean;
  trailEnabled: boolean;
  customImageUrl?: string;
  videoQuality: VideoQuality;
}

export const ANGEL_COLORS: AngelColorConfig[] = [
  {
    id: 'white',
    name: 'Pure Light',
    hsl: '0 0% 100%',
    glowColor: 'rgba(255, 255, 255, 0.6)',
  },
  {
    id: 'gold',
    name: 'Divine Gold',
    hsl: '45 100% 70%',
    glowColor: 'rgba(255, 215, 100, 0.6)',
  },
  {
    id: 'blue',
    name: 'Celestial Blue',
    hsl: '210 80% 75%',
    glowColor: 'rgba(150, 200, 255, 0.6)',
  },
  {
    id: 'pink',
    name: 'Rose Grace',
    hsl: '330 70% 80%',
    glowColor: 'rgba(255, 180, 200, 0.6)',
  },
  {
    id: 'green',
    name: 'Healing Light',
    hsl: '140 50% 70%',
    glowColor: 'rgba(150, 220, 170, 0.6)',
  },
  {
    id: 'purple',
    name: 'Sacred Violet',
    hsl: '270 60% 75%',
    glowColor: 'rgba(200, 160, 255, 0.6)',
  },
];

export const ANGEL_STYLES: AngelStyleConfig[] = [
  {
    id: 'classic',
    name: 'Classic Angel',
    description: 'Soft wings with white glow',
    glowIntensity: 0.6,
    glowColor: 'rgba(255,255,255,0.6)',
    scale: 1,
    animation: {
      floatDuration: 3,
      floatAmplitude: 4,
      flapDuration: 2.5,
      followEasing: 0.12,
      sparkleIntensity: 1,
      trailIntensity: 1,
    },
  },
  {
    id: 'cherub',
    name: 'Cherub',
    description: 'Small, gentle, child-friendly',
    glowIntensity: 0.5,
    glowColor: 'rgba(255,245,220,0.6)',
    scale: 0.8,
    animation: {
      floatDuration: 2.2,
      floatAmplitude: 5,
      flapDuration: 1.8,
      followEasing: 0.15,
      sparkleIntensity: 0.7,
      trailIntensity: 0.6,
      bouncy: true,
    },
  },
  {
    id: 'seraph',
    name: 'Seraph',
    description: 'Light-based, radiant wings',
    glowIntensity: 0.8,
    glowColor: 'rgba(255,255,240,0.7)',
    scale: 1.1,
    animation: {
      floatDuration: 4,
      floatAmplitude: 3,
      followEasing: 0.08,
      sparkleIntensity: 1.3,
      trailIntensity: 1.2,
      pulseGlow: true,
    },
  },
  {
    id: 'guardian',
    name: 'Guardian Angel',
    description: 'Tall, protective presence',
    glowIntensity: 0.55,
    glowColor: 'rgba(240,248,255,0.6)',
    scale: 1.2,
    animation: {
      floatDuration: 3.5,
      floatAmplitude: 2.5,
      followEasing: 0.1,
      sparkleIntensity: 0.8,
      trailIntensity: 0.9,
      pulseGlow: true,
    },
  },
  {
    id: 'joy',
    name: 'Joy Angel',
    description: 'Uplifting, playful spirit',
    glowIntensity: 0.65,
    glowColor: 'rgba(255,250,240,0.65)',
    scale: 1,
    animation: {
      floatDuration: 2.5,
      floatAmplitude: 6,
      flapDuration: 2,
      followEasing: 0.14,
      sparkleIntensity: 1.2,
      trailIntensity: 1.1,
      bouncy: true,
    },
  },
  {
    id: 'peace',
    name: 'Peace Angel',
    description: 'Serene, calming presence',
    glowIntensity: 0.5,
    glowColor: 'rgba(245,250,255,0.6)',
    scale: 1.05,
    animation: {
      floatDuration: 4.5,
      floatAmplitude: 2,
      followEasing: 0.07,
      sparkleIntensity: 0.6,
      trailIntensity: 0.7,
    },
  },
  {
    id: 'healing',
    name: 'Healing Angel',
    description: 'Gentle, restorative energy',
    glowIntensity: 0.6,
    glowColor: 'rgba(250,255,250,0.6)',
    scale: 1.1,
    animation: {
      floatDuration: 3.8,
      floatAmplitude: 3,
      followEasing: 0.09,
      sparkleIntensity: 0.9,
      trailIntensity: 0.8,
      pulseGlow: true,
    },
  },
  {
    id: 'fairy',
    name: 'Fairy Angel',
    description: 'Whimsical, magical spirit',
    glowIntensity: 0.7,
    glowColor: 'rgba(255,220,255,0.6)',
    scale: 1,
    animation: {
      floatDuration: 2.8,
      floatAmplitude: 5,
      flapDuration: 2.8,
      followEasing: 0.13,
      sparkleIntensity: 1.4,
      trailIntensity: 1.3,
      bouncy: true,
    },
  },
  {
    id: 'fairy-blue',
    name: 'Blue Fairy',
    description: 'Serene blue fairy with elegant wings',
    glowIntensity: 0.65,
    glowColor: 'rgba(150,200,255,0.6)',
    scale: 1,
    animation: {
      floatDuration: 3,
      floatAmplitude: 4,
      flapDuration: 2.5,
      followEasing: 0.12,
      sparkleIntensity: 1.2,
      trailIntensity: 1.1,
      bouncy: true,
    },
  },
  {
    id: 'fairy-red',
    name: 'Red Fairy',
    description: 'Playful fairy with colorful wings',
    glowIntensity: 0.7,
    glowColor: 'rgba(255,150,180,0.6)',
    scale: 1,
    animation: {
      floatDuration: 2.5,
      floatAmplitude: 5,
      flapDuration: 2.2,
      followEasing: 0.14,
      sparkleIntensity: 1.3,
      trailIntensity: 1.2,
      bouncy: true,
    },
  },
  {
    id: 'fairy-pink',
    name: 'Pink Fairy',
    description: 'Graceful fairy with pink & gold wings',
    glowIntensity: 0.68,
    glowColor: 'rgba(255,180,200,0.6)',
    scale: 1,
    animation: {
      floatDuration: 2.8,
      floatAmplitude: 4.5,
      flapDuration: 2.4,
      followEasing: 0.13,
      sparkleIntensity: 1.25,
      trailIntensity: 1.15,
      bouncy: true,
    },
  },
  {
    id: 'fairy-mint',
    name: 'Mint Fairy',
    description: 'Sweet fairy with mint green wings',
    glowIntensity: 0.6,
    glowColor: 'rgba(180,255,220,0.6)',
    scale: 1,
    animation: {
      floatDuration: 3.2,
      floatAmplitude: 4,
      flapDuration: 2.6,
      followEasing: 0.11,
      sparkleIntensity: 1.1,
      trailIntensity: 1.0,
      bouncy: true,
    },
  },
  {
    id: 'fairy-gold',
    name: 'Tiên Nữ Vàng Kim',
    description: 'Tiên nữ xinh đẹp với đôi cánh vàng kim lấp lánh',
    glowIntensity: 0.72,
    glowColor: 'rgba(218,165,32,0.65)',
    scale: 1.05,
    animation: {
      floatDuration: 2.8,
      floatAmplitude: 4.5,
      flapDuration: 2.4,
      followEasing: 0.13,
      sparkleIntensity: 1.3,
      trailIntensity: 1.2,
      bouncy: true,
    },
  },
  {
    id: 'fairy-yellow',
    name: 'Tiên Nữ Ánh Dương',
    description: 'Tiên nữ vàng rực rỡ bay giữa những cánh bướm',
    glowIntensity: 0.7,
    glowColor: 'rgba(255,215,0,0.65)',
    scale: 1,
    animation: {
      floatDuration: 2.5,
      floatAmplitude: 5,
      flapDuration: 2.2,
      followEasing: 0.14,
      sparkleIntensity: 1.35,
      trailIntensity: 1.25,
      bouncy: true,
    },
  },
  {
    id: 'fairy-green',
    name: 'Tiên Nữ Rừng Xanh',
    description: 'Tiên nữ thiên nhiên với đôi cánh xanh mướt',
    glowIntensity: 0.65,
    glowColor: 'rgba(144,238,144,0.6)',
    scale: 1.1,
    animation: {
      floatDuration: 3.5,
      floatAmplitude: 3.5,
      flapDuration: 2.8,
      followEasing: 0.1,
      sparkleIntensity: 1.0,
      trailIntensity: 0.95,
      bouncy: true,
    },
  },
  {
    id: 'fairy-tinker',
    name: 'Tiên Nữ Tinker',
    description: 'Tiên nữ nhỏ nhắn vui tươi rắc bụi sao',
    glowIntensity: 0.68,
    glowColor: 'rgba(180,255,180,0.6)',
    scale: 0.95,
    animation: {
      floatDuration: 2.2,
      floatAmplitude: 5.5,
      flapDuration: 1.8,
      followEasing: 0.16,
      sparkleIntensity: 1.5,
      trailIntensity: 1.4,
      bouncy: true,
    },
  },
  {
    id: 'fairy-cute',
    name: 'Tiên Nữ Dễ Thương',
    description: 'Tiên nữ đáng yêu ngồi thư giãn trên đám mây',
    glowIntensity: 0.62,
    glowColor: 'rgba(255,182,193,0.6)',
    scale: 0.9,
    animation: {
      floatDuration: 3.5,
      floatAmplitude: 3,
      flapDuration: 3,
      followEasing: 0.09,
      sparkleIntensity: 0.9,
      trailIntensity: 0.85,
      bouncy: true,
    },
  },
  {
    id: 'fairy-star',
    name: 'Tiên Nữ Ngôi Sao',
    description: 'Tiên nữ nhỏ xinh cầm đũa phép sao',
    glowIntensity: 0.7,
    glowColor: 'rgba(255,223,140,0.65)',
    scale: 0.9,
    animation: {
      floatDuration: 2.5,
      floatAmplitude: 5,
      flapDuration: 2,
      followEasing: 0.15,
      sparkleIntensity: 1.4,
      trailIntensity: 1.3,
      bouncy: true,
    },
  },
  {
    id: 'fairy-leaf',
    name: 'Tiên Nữ Lá Xanh',
    description: 'Tiên nữ nhỏ nhắn với đôi cánh lấp lánh',
    glowIntensity: 0.68,
    glowColor: 'rgba(180,220,100,0.6)',
    scale: 0.95,
    animation: {
      floatDuration: 2.8,
      floatAmplitude: 4.5,
      flapDuration: 2.2,
      followEasing: 0.14,
      sparkleIntensity: 1.3,
      trailIntensity: 1.2,
      bouncy: true,
    },
  },
  {
    id: 'fairy-sunny',
    name: 'Tiên Nữ Ánh Nắng',
    description: 'Tiên nữ váy vàng rực rỡ tươi vui',
    glowIntensity: 0.72,
    glowColor: 'rgba(255,215,0,0.65)',
    scale: 0.95,
    animation: {
      floatDuration: 2.4,
      floatAmplitude: 5.2,
      flapDuration: 2,
      followEasing: 0.15,
      sparkleIntensity: 1.35,
      trailIntensity: 1.25,
      bouncy: true,
    },
  },
  {
    id: 'fairy-butterfly',
    name: 'Tiên Nữ Cánh Bướm',
    description: 'Tiên nữ với đôi cánh bướm xanh lá',
    glowIntensity: 0.65,
    glowColor: 'rgba(144,238,144,0.6)',
    scale: 1.05,
    animation: {
      floatDuration: 3.2,
      floatAmplitude: 4,
      flapDuration: 2.5,
      followEasing: 0.11,
      sparkleIntensity: 1.1,
      trailIntensity: 1.0,
      bouncy: true,
    },
  },
  {
    id: 'fairy-spring',
    name: 'Tiên Nữ Mùa Xuân',
    description: 'Tiên nữ bay lượn với cánh bướm hồng',
    glowIntensity: 0.7,
    glowColor: 'rgba(255,150,180,0.6)',
    scale: 1,
    animation: {
      floatDuration: 2.6,
      floatAmplitude: 5,
      flapDuration: 2.2,
      followEasing: 0.14,
      sparkleIntensity: 1.25,
      trailIntensity: 1.15,
      bouncy: true,
    },
  },
  {
    id: 'fairy-heart',
    name: 'Tiên Nữ Trái Tim',
    description: 'Tiên nữ dễ thương ngồi trên trái tim hồng',
    glowIntensity: 0.68,
    glowColor: 'rgba(255,182,193,0.65)',
    scale: 0.9,
    animation: {
      floatDuration: 3.5,
      floatAmplitude: 3.5,
      flapDuration: 3,
      followEasing: 0.1,
      sparkleIntensity: 1.0,
      trailIntensity: 0.95,
      bouncy: true,
    },
  },
  {
    id: 'fairy-love',
    name: 'Tiên Nữ Tình Yêu',
    description: 'Tiên nữ váy trắng trong trái tim yêu thương',
    glowIntensity: 0.7,
    glowColor: 'rgba(255,105,180,0.6)',
    scale: 0.95,
    animation: {
      floatDuration: 3.2,
      floatAmplitude: 3.8,
      flapDuration: 2.8,
      followEasing: 0.11,
      sparkleIntensity: 1.1,
      trailIntensity: 1.0,
      bouncy: true,
    },
  },
  {
    id: 'fairy-lavender',
    name: 'Tiên Nữ Oải Hương',
    description: 'Tiên nữ xinh đẹp với váy tím lavender',
    glowIntensity: 0.72,
    glowColor: 'rgba(200,160,255,0.65)',
    scale: 1.05,
    animation: {
      floatDuration: 3,
      floatAmplitude: 4,
      flapDuration: 2.6,
      followEasing: 0.12,
      sparkleIntensity: 1.2,
      trailIntensity: 1.1,
      bouncy: true,
    },
  },
  {
    id: 'fairy-rosemary',
    name: 'Tiên Nữ Hương Thảo',
    description: 'Tiên nữ xinh đẹp váy đỏ cánh xanh lục',
    glowIntensity: 0.7,
    glowColor: 'rgba(144,238,144,0.65)',
    scale: 1,
    animation: {
      floatDuration: 2.8,
      floatAmplitude: 4.5,
      flapDuration: 2.4,
      followEasing: 0.13,
      sparkleIntensity: 1.3,
      trailIntensity: 1.2,
      bouncy: true,
    },
  },
  {
    id: 'fairy-butterfly-gold',
    name: 'Tiên Nữ Cánh Bướm Vàng',
    description: 'Tiên nữ tóc vàng với đôi cánh bướm trắng-vàng',
    glowIntensity: 0.72,
    glowColor: 'rgba(218,165,32,0.65)',
    scale: 1.05,
    animation: {
      floatDuration: 3.2,
      floatAmplitude: 4,
      flapDuration: 2.6,
      followEasing: 0.11,
      sparkleIntensity: 1.15,
      trailIntensity: 1.05,
      bouncy: true,
    },
  },
  {
    id: 'fairy-sunflower',
    name: 'Tiên Nữ Hướng Dương',
    description: 'Tiên nữ bé nhỏ váy vàng tươi vui',
    glowIntensity: 0.68,
    glowColor: 'rgba(255,215,0,0.6)',
    scale: 0.9,
    animation: {
      floatDuration: 2.4,
      floatAmplitude: 5,
      flapDuration: 2,
      followEasing: 0.15,
      sparkleIntensity: 1.35,
      trailIntensity: 1.25,
      bouncy: true,
    },
  },
  {
    id: 'fairy-peach',
    name: 'Tiên Nữ Đào Hồng',
    description: 'Tiên nữ xinh đẹp cánh bướm hồng cam',
    glowIntensity: 0.7,
    glowColor: 'rgba(255,180,150,0.65)',
    scale: 1.05,
    animation: {
      floatDuration: 2.6,
      floatAmplitude: 4.5,
      flapDuration: 2.3,
      followEasing: 0.13,
      sparkleIntensity: 1.25,
      trailIntensity: 1.15,
      bouncy: true,
    },
  },
  {
    id: 'fairy-lime',
    name: 'Tiên Nữ Xanh Chanh',
    description: 'Tiên nữ đáng yêu váy xanh lá nhạt',
    glowIntensity: 0.65,
    glowColor: 'rgba(180,238,180,0.6)',
    scale: 1,
    animation: {
      floatDuration: 3,
      floatAmplitude: 4,
      flapDuration: 2.5,
      followEasing: 0.12,
      sparkleIntensity: 1.2,
      trailIntensity: 1.1,
      bouncy: true,
    },
  },
  {
    id: 'fairy-ruby',
    name: 'Tiên Nữ Hồng Ngọc',
    description: 'Tiên nữ đỏ rực với mũ và cánh bướm bạc',
    glowIntensity: 0.72,
    glowColor: 'rgba(220,50,50,0.65)',
    scale: 1.05,
    animation: {
      floatDuration: 2.8,
      floatAmplitude: 4.5,
      flapDuration: 2.4,
      followEasing: 0.13,
      sparkleIntensity: 1.3,
      trailIntensity: 1.2,
      bouncy: true,
    },
  },
  {
    id: 'fairy-ocean',
    name: 'Tiên Nữ Đại Dương',
    description: 'Tiên nữ váy xanh biển bay bổng nhẹ nhàng',
    glowIntensity: 0.68,
    glowColor: 'rgba(100,200,220,0.6)',
    scale: 1,
    animation: {
      floatDuration: 3.2,
      floatAmplitude: 4,
      flapDuration: 2.6,
      followEasing: 0.11,
      sparkleIntensity: 1.15,
      trailIntensity: 1.05,
      bouncy: true,
    },
  },
  {
    id: 'fairy-sakura',
    name: 'Tiên Nữ Anh Đào',
    description: 'Tiên nữ hồng nhạt dịu dàng như hoa anh đào',
    glowIntensity: 0.65,
    glowColor: 'rgba(255,182,193,0.6)',
    scale: 0.95,
    animation: {
      floatDuration: 3,
      floatAmplitude: 4,
      flapDuration: 2.5,
      followEasing: 0.12,
      sparkleIntensity: 1.2,
      trailIntensity: 1.1,
      bouncy: true,
    },
  },
  {
    id: 'fairy-cherry-blossom',
    name: 'Tiên Nữ Hoa Đào',
    description: 'Tiên nữ xinh đẹp giữa những cánh hoa đào',
    glowIntensity: 0.7,
    glowColor: 'rgba(255,150,180,0.65)',
    scale: 1.1,
    animation: {
      floatDuration: 2.6,
      floatAmplitude: 5,
      flapDuration: 2.3,
      followEasing: 0.14,
      sparkleIntensity: 1.35,
      trailIntensity: 1.25,
      bouncy: true,
    },
  },
  {
    id: 'fairy-doll',
    name: 'Tiên Nữ Búp Bê',
    description: 'Tiên nữ nhỏ nhắn dễ thương như búp bê',
    glowIntensity: 0.62,
    glowColor: 'rgba(255,192,203,0.6)',
    scale: 0.85,
    animation: {
      floatDuration: 3.5,
      floatAmplitude: 3.5,
      flapDuration: 3,
      followEasing: 0.1,
      sparkleIntensity: 1.0,
      trailIntensity: 0.95,
      bouncy: true,
    },
  },
  {
    id: 'fairy-rainbow',
    name: 'Tiên Nữ Cầu Vồng',
    description: 'Tiên nữ xinh xắn với đôi cánh và váy cầu vồng rực rỡ',
    glowIntensity: 0.75,
    glowColor: 'rgba(255,180,220,0.65)',
    scale: 1.05,
    animation: {
      floatDuration: 3.5,
      floatAmplitude: 3.5,
      flapDuration: 3,
      followEasing: 0.1,
      sparkleIntensity: 1.3,
      trailIntensity: 1.2,
      bouncy: true,
    },
  },
  {
    id: 'fairy-colorful',
    name: 'Tiên Nữ Sắc Màu',
    description: 'Tiên nữ tóc cầu vồng với đôi cánh rực rỡ',
    glowIntensity: 0.72,
    glowColor: 'rgba(255,150,100,0.65)',
    scale: 0.9,
    animation: {
      floatDuration: 2.6,
      floatAmplitude: 5,
      flapDuration: 2.2,
      followEasing: 0.14,
      sparkleIntensity: 1.4,
      trailIntensity: 1.3,
      bouncy: true,
    },
  },
  {
    id: 'fairy-pencil',
    name: 'Tiên Nữ Bút Chì',
    description: 'Tiên nữ dễ thương ngồi trên bút chì sáng tạo',
    glowIntensity: 0.68,
    glowColor: 'rgba(255,182,193,0.6)',
    scale: 0.95,
    animation: {
      floatDuration: 3,
      floatAmplitude: 4,
      flapDuration: 2.5,
      followEasing: 0.12,
      sparkleIntensity: 1.2,
      trailIntensity: 1.1,
      bouncy: true,
    },
  },
  {
    id: 'fairy-teal',
    name: 'Tiên Nữ Xanh Ngọc',
    description: 'Tiên nữ váy dài xanh ngọc thanh lịch',
    glowIntensity: 0.65,
    glowColor: 'rgba(100,180,180,0.6)',
    scale: 1.1,
    animation: {
      floatDuration: 3.5,
      floatAmplitude: 3,
      flapDuration: 2.8,
      followEasing: 0.1,
      sparkleIntensity: 1.0,
      trailIntensity: 0.95,
      bouncy: true,
    },
  },
  {
    id: 'fairy-violet',
    name: 'Tiên Nữ Tím Hồng',
    description: 'Tiên nữ tóc hồng với váy tím lavender',
    glowIntensity: 0.68,
    glowColor: 'rgba(200,150,220,0.6)',
    scale: 0.95,
    animation: {
      floatDuration: 3.2,
      floatAmplitude: 4,
      flapDuration: 2.6,
      followEasing: 0.11,
      sparkleIntensity: 1.15,
      trailIntensity: 1.05,
      bouncy: true,
    },
  },
  {
    id: 'fairy-strawberry',
    name: 'Tiên Nữ Dâu Đỏ',
    description: 'Tiên nữ váy đỏ bay lượn vui tươi',
    glowIntensity: 0.7,
    glowColor: 'rgba(220,80,80,0.65)',
    scale: 1,
    animation: {
      floatDuration: 2.4,
      floatAmplitude: 5.5,
      flapDuration: 2,
      followEasing: 0.15,
      sparkleIntensity: 1.35,
      trailIntensity: 1.25,
      bouncy: true,
    },
  },
  {
    id: 'fairy-mint-star',
    name: 'Tiên Nữ Ngôi Sao Xanh',
    description: 'Tiên nữ dễ thương cầm đũa phép ngôi sao',
    glowIntensity: 0.68,
    glowColor: 'rgba(150,220,200,0.6)',
    scale: 0.9,
    animation: {
      floatDuration: 2.6,
      floatAmplitude: 5,
      flapDuration: 2.2,
      followEasing: 0.14,
      sparkleIntensity: 1.35,
      trailIntensity: 1.25,
      bouncy: true,
    },
  },
  {
    id: 'fairy-pink-star',
    name: 'Tiên Nữ Sao Hồng',
    description: 'Tiên nữ váy hồng với cánh bướm cầu vồng',
    glowIntensity: 0.7,
    glowColor: 'rgba(255,182,220,0.65)',
    scale: 0.9,
    animation: {
      floatDuration: 2.5,
      floatAmplitude: 5,
      flapDuration: 2,
      followEasing: 0.15,
      sparkleIntensity: 1.4,
      trailIntensity: 1.3,
      bouncy: true,
    },
  },
  {
    id: 'fairy-rose-dress',
    name: 'Tiên Nữ Váy Hoa Hồng',
    description: 'Tiên nữ xinh đẹp với váy hồng dài thướt tha',
    glowIntensity: 0.72,
    glowColor: 'rgba(255,150,180,0.65)',
    scale: 1.15,
    animation: {
      floatDuration: 3.5,
      floatAmplitude: 3,
      flapDuration: 3,
      followEasing: 0.09,
      sparkleIntensity: 1.1,
      trailIntensity: 1.0,
      bouncy: true,
    },
  },
  {
    id: 'fairy-golden-sit',
    name: 'Tiên Nữ Vàng Ngồi',
    description: 'Tiên nữ váy vàng ánh kim duyên dáng',
    glowIntensity: 0.75,
    glowColor: 'rgba(255,215,0,0.7)',
    scale: 1,
    animation: {
      floatDuration: 3.8,
      floatAmplitude: 2.5,
      flapDuration: 3.2,
      followEasing: 0.08,
      sparkleIntensity: 0.9,
      trailIntensity: 0.85,
      pulseGlow: true,
    },
  },
  {
    id: 'fairy-nature-wings',
    name: 'Tiên Nữ Thiên Nhiên',
    description: 'Tiên nữ với đôi cánh xanh lá rộng lớn',
    glowIntensity: 0.68,
    glowColor: 'rgba(100,180,100,0.6)',
    scale: 1.1,
    animation: {
      floatDuration: 3.5,
      floatAmplitude: 3,
      flapDuration: 2.8,
      followEasing: 0.1,
      sparkleIntensity: 1.0,
      trailIntensity: 0.95,
      bouncy: true,
    },
  },
  {
    id: 'fairy-butterfly-colorful',
    name: 'Tiên Nữ Bướm Sắc Màu',
    description: 'Tiên nữ với cánh bướm xanh tím rực rỡ',
    glowIntensity: 0.72,
    glowColor: 'rgba(100,200,220,0.65)',
    scale: 1.05,
    animation: {
      floatDuration: 3,
      floatAmplitude: 4,
      flapDuration: 2.5,
      followEasing: 0.12,
      sparkleIntensity: 1.25,
      trailIntensity: 1.15,
      bouncy: true,
    },
  },
  {
    id: 'fairy-rainbow-wings',
    name: 'Tiên Nữ Cánh Cầu Vồng',
    description: 'Tiên nữ nhỏ nhắn với cánh bướm cầu vồng',
    glowIntensity: 0.7,
    glowColor: 'rgba(255,180,200,0.65)',
    scale: 0.95,
    animation: {
      floatDuration: 2.6,
      floatAmplitude: 5,
      flapDuration: 2.2,
      followEasing: 0.14,
      sparkleIntensity: 1.35,
      trailIntensity: 1.25,
      bouncy: true,
    },
  },
  {
    id: 'fairy-galaxy',
    name: 'Tiên Nữ Thiên Hà',
    description: 'Tiên nữ cánh bướm lấp lánh như dải ngân hà',
    glowIntensity: 0.75,
    glowColor: 'rgba(180,150,255,0.7)',
    scale: 1,
    animation: {
      floatDuration: 3,
      floatAmplitude: 4,
      flapDuration: 2.5,
      followEasing: 0.12,
      sparkleIntensity: 1.4,
      trailIntensity: 1.3,
      bouncy: true,
      pulseGlow: true,
    },
  },
  {
    id: 'fairy-purple-flower',
    name: 'Tiên Nữ Hoa Tím',
    description: 'Tiên nữ ngồi giữa những cánh hoa tím',
    glowIntensity: 0.72,
    glowColor: 'rgba(180,100,220,0.65)',
    scale: 1.1,
    animation: {
      floatDuration: 3.8,
      floatAmplitude: 2.5,
      flapDuration: 3.2,
      followEasing: 0.08,
      sparkleIntensity: 0.9,
      trailIntensity: 0.85,
      pulseGlow: true,
    },
  },
  {
    id: 'fairy-violet-bloom',
    name: 'Tiên Nữ Hoa Violet',
    description: 'Tiên nữ tím hồng bay giữa những bông hoa',
    glowIntensity: 0.7,
    glowColor: 'rgba(200,100,220,0.65)',
    scale: 0.95,
    animation: {
      floatDuration: 2.8,
      floatAmplitude: 4.5,
      flapDuration: 2.4,
      followEasing: 0.13,
      sparkleIntensity: 1.3,
      trailIntensity: 1.2,
      bouncy: true,
    },
  },
  {
    id: 'fairy-video',
    name: 'Animated Fairy',
    description: 'Magical animated fairy video',
    glowIntensity: 0.75,
    glowColor: 'rgba(255,220,255,0.7)',
    scale: 1.1,
    isVideo: true,
    animation: {
      floatDuration: 3,
      floatAmplitude: 4,
      flapDuration: 2.5,
      followEasing: 0.12,
      sparkleIntensity: 1.4,
      trailIntensity: 1.3,
      bouncy: true,
    },
  },
  {
    id: 'celestial-video',
    name: 'Celestial Video',
    description: 'Mesmerizing celestial video angel',
    glowIntensity: 0.7,
    glowColor: 'rgba(200,220,255,0.65)',
    scale: 1.15,
    isVideo: true,
    animation: {
      floatDuration: 3.5,
      floatAmplitude: 3.5,
      flapDuration: 3,
      followEasing: 0.1,
      sparkleIntensity: 0.8,
      trailIntensity: 0.9,
      pulseGlow: true,
    },
  },
  {
    id: 'starlight-seraph',
    name: 'Starlight Seraph',
    description: 'Shimmering starlight and stardust angel',
    glowIntensity: 0.75,
    glowColor: 'rgba(255,250,220,0.7)',
    scale: 1.1,
    isVideo: true,
    animation: {
      floatDuration: 3.2,
      floatAmplitude: 3,
      flapDuration: 2.8,
      followEasing: 0.09,
      sparkleIntensity: 1.2,
      trailIntensity: 1.0,
      pulseGlow: true,
    },
  },
  {
    id: 'aurora-guardian',
    name: 'Aurora Guardian',
    description: 'Divine guardian of northern lights',
    glowIntensity: 0.72,
    glowColor: 'rgba(100,220,180,0.65)',
    scale: 1.2,
    isVideo: true,
    animation: {
      floatDuration: 3.8,
      floatAmplitude: 2.5,
      flapDuration: 3.2,
      followEasing: 0.08,
      sparkleIntensity: 0.7,
      trailIntensity: 1.1,
      pulseGlow: true,
    },
  },
  {
    id: 'nebula-messenger',
    name: 'Nebula Messenger',
    description: 'Cosmic messenger from the nebulae',
    glowIntensity: 0.78,
    glowColor: 'rgba(200,150,255,0.7)',
    scale: 1.15,
    isVideo: true,
    animation: {
      floatDuration: 3.5,
      floatAmplitude: 3.5,
      flapDuration: 3,
      followEasing: 0.1,
      sparkleIntensity: 0.9,
      trailIntensity: 1.0,
      pulseGlow: true,
    },
  },
  {
    id: 'grok-angel-1',
    name: 'Grok Angel I',
    description: 'Thiên thần thần thánh lung linh',
    glowIntensity: 0.72,
    glowColor: 'rgba(255,240,200,0.7)',
    scale: 1.1,
    isVideo: true,
    animation: {
      floatDuration: 3.2,
      floatAmplitude: 3.5,
      flapDuration: 2.8,
      followEasing: 0.1,
      sparkleIntensity: 1.1,
      trailIntensity: 1.0,
      pulseGlow: true,
    },
  },
  {
    id: 'grok-angel-2',
    name: 'Grok Angel II',
    description: 'Thiên thần ánh sáng huyền bí',
    glowIntensity: 0.75,
    glowColor: 'rgba(220,200,255,0.7)',
    scale: 1.15,
    isVideo: true,
    animation: {
      floatDuration: 3.5,
      floatAmplitude: 3,
      flapDuration: 3,
      followEasing: 0.09,
      sparkleIntensity: 1.0,
      trailIntensity: 1.1,
      pulseGlow: true,
    },
  },
  {
    id: 'grok-angel-3',
    name: 'Grok Angel III',
    description: 'Thiên thần vũ trụ thiêng liêng',
    glowIntensity: 0.78,
    glowColor: 'rgba(180,220,255,0.7)',
    scale: 1.12,
    isVideo: true,
    animation: {
      floatDuration: 3.4,
      floatAmplitude: 3.2,
      flapDuration: 2.9,
      followEasing: 0.1,
      sparkleIntensity: 1.2,
      trailIntensity: 1.0,
      pulseGlow: true,
    },
  },
  {
    id: 'fairy-easter',
    name: 'Tiên Nữ Phục Sinh',
    description: 'Tiên nữ xinh xắn với giỏ trứng Phục Sinh đầy màu sắc',
    glowIntensity: 0.68,
    glowColor: 'rgba(255,200,220,0.65)',
    scale: 1,
    animation: {
      floatDuration: 2.8,
      floatAmplitude: 4.5,
      flapDuration: 2.4,
      followEasing: 0.13,
      sparkleIntensity: 1.3,
      trailIntensity: 1.2,
      bouncy: true,
    },
  },
  {
    id: 'fairy-prayer',
    name: 'Thiên Thần Cầu Nguyện',
    description: 'Thiên thần tóc vàng với đôi cánh cầu vồng đang cầu nguyện',
    glowIntensity: 0.72,
    glowColor: 'rgba(200,220,255,0.7)',
    scale: 1.05,
    animation: {
      floatDuration: 3.5,
      floatAmplitude: 3,
      flapDuration: 3,
      followEasing: 0.09,
      sparkleIntensity: 1.0,
      trailIntensity: 0.95,
      pulseGlow: true,
    },
  },
  {
    id: 'fairy-tinkerbell',
    name: 'Tiên Nữ Tinkerbell',
    description: 'Tiên nữ xanh lá quyến rũ với đôi cánh lấp lánh',
    glowIntensity: 0.7,
    glowColor: 'rgba(150,255,150,0.65)',
    scale: 1.1,
    animation: {
      floatDuration: 2.4,
      floatAmplitude: 5.5,
      flapDuration: 2,
      followEasing: 0.15,
      sparkleIntensity: 1.45,
      trailIntensity: 1.35,
      bouncy: true,
    },
  },
  {
    id: 'grok-angel-4',
    name: 'Grok Angel IV',
    description: 'Thiên thần thần kỳ với ánh sáng huyền bí',
    glowIntensity: 0.75,
    glowColor: 'rgba(200,180,255,0.7)',
    scale: 1.1,
    isVideo: true,
    animation: {
      floatDuration: 3.2,
      floatAmplitude: 3.5,
      flapDuration: 2.6,
      followEasing: 0.11,
      sparkleIntensity: 1.15,
      trailIntensity: 1.05,
      pulseGlow: true,
    },
  },
  {
    id: 'grok-angel-5',
    name: 'Grok Angel V',
    description: 'Thiên thần linh thiêng tỏa sáng',
    glowIntensity: 0.78,
    glowColor: 'rgba(255,200,180,0.7)',
    scale: 1.12,
    isVideo: true,
    animation: {
      floatDuration: 3.0,
      floatAmplitude: 3.8,
      flapDuration: 2.5,
      followEasing: 0.12,
      sparkleIntensity: 1.2,
      trailIntensity: 1.1,
      pulseGlow: true,
    },
  },
  {
    id: 'grok-angel-6',
    name: 'Grok Angel VI',
    description: 'Thiên thần vũ trụ huyền diệu',
    glowIntensity: 0.76,
    glowColor: 'rgba(180,255,220,0.7)',
    scale: 1.08,
    isVideo: true,
    animation: {
      floatDuration: 3.3,
      floatAmplitude: 3.2,
      flapDuration: 2.7,
      followEasing: 0.1,
      sparkleIntensity: 1.1,
      trailIntensity: 1.0,
      pulseGlow: true,
    },
  },
  {
    id: 'grok-angel-7',
    name: 'Grok Angel VII',
    description: 'Thiên thần ánh sáng thiên đường',
    glowIntensity: 0.8,
    glowColor: 'rgba(255,220,180,0.7)',
    scale: 1.15,
    isVideo: true,
    animation: {
      floatDuration: 2.8,
      floatAmplitude: 4.0,
      flapDuration: 2.4,
      followEasing: 0.13,
      sparkleIntensity: 1.25,
      trailIntensity: 1.15,
      pulseGlow: true,
    },
  },
  {
    id: 'grok-angel-8',
    name: 'Grok Angel VIII',
    description: 'Thiên thần thánh linh cao quý',
    glowIntensity: 0.82,
    glowColor: 'rgba(220,200,255,0.7)',
    scale: 1.18,
    isVideo: true,
    animation: {
      floatDuration: 3.5,
      floatAmplitude: 2.8,
      flapDuration: 3.0,
      followEasing: 0.09,
      sparkleIntensity: 1.0,
      trailIntensity: 0.95,
      pulseGlow: true,
    },
  },
];
